#!/usr/bin/env bash

[ "$0" = 'bash' ] ||
exec /usr/bin/env bash --rcfile "$0" "$@"

# source .bashrc file
[ -r ~/.bashrc ] && {
  . ~/.bashrc
}

# Navigate to folder
cd ~/ACM

# FUNCTIONS ====================================================================

# Compile c++
function compile() {
	g++ -g -std=c++17 ${1/.cpp}.cpp -o ${1/.cpp} -O2 -Wall -Wno-sign-compare -Wfatal-errors -Wshadow
}

# Open vim, default to .cpp
function vicpp() {
  if [ -f ${1/.cpp}.cpp ]; then
    vim ${1/.cpp}.cpp
  elif [ -f ${1/.py}.py ]; then
    vim ${1/.py}.py
  elif [ -f ${1} ]; then
    vim ${1}
  else
    vim ${1}
  fi
}

function watch() {
  submit.py $@ -w
}

function all() {
  submit.py $@ -wt
}

# Create new folder and symlink it
function init() {
  if [ "$#" -ne 1 ]; then
    echo "init requires exactly one argument"
    return -1
  fi
  if [ -d ./cur ]; then
    rm -f ./cur
  fi
  if [ ! -d $1 ]; then
    mkdir $1
  fi
  ln -s $1 cur
  cd cur
}

# PROMPT =======================================================================

PS1='[ACM]:\w\$ '

# ALIASES ======================================================================

alias rem='echo is best girl'
alias ++='compile'
alias sm='submit.py'
alias wa='watch'
alias vi='vicpp'
