#!/bin/sh
set -e

if [ "$#" -eq 0 ]
then
	echo "${GRE}Usage: $0 {file.cpp} ${NC}"
else
	# Check that the code file is valid
	FILE=$1
	if [ ! -f $FILE ]
	then
		echo "${RED}Code file: ${FILE} is invalid!${NC}"
		exit
	fi

	# Compiling the c/cpp file
	EXT="${FILE#*.}"
	OUT="${FILE%%.*}.out"
	if [ "${EXT}" = "cpp" ]
	then
		echo "${GRE}Compiling ${FILE} ...${NC}"
		g++ -o $OUT $FILE -Wall -Wpedantic -Wextra -Wno-sign-compare
	else
		echo "${RED}.${EXT} file extension not recognized.${NC}"
		exit
	fi
	echo "./${OUT}"
	./$OUT
	rm $OUT
fi
